import { app, type BrowserWindow } from 'electron';
import { autoUpdater } from 'electron-updater';
import { IPC_EVENT, type UpdateStatus } from '@greenroom/shared';

const CHECK_INTERVAL_MS = 4 * 60 * 60 * 1000;
const INITIAL_CHECK_DELAY_MS = 8_000;
const UP_TO_DATE_VISIBLE_MS = 3_500;
// A check should resolve quickly; if electron-updater never fires an event we
// surface a timeout instead of leaving the button stuck on "Checking…".
const CHECK_TIMEOUT_MS = 30_000;

function readableUpdateError(error: Error): string {
  const raw = error.message || String(error);
  if (/net::|network|enotfound|eai_|econn|timed out|timeout/i.test(raw)) {
    return 'Greenroom could not reach the update server. Check your connection and try again.';
  }
  // app-update.yml is generated by electron-builder from the publish block; if it's
  // absent the install predates update support and a reinstall is the only fix.
  if (/app-update\.yml|ENOENT|no such file|provider/i.test(raw)) {
    return 'This install cannot self-update. Download the latest installer from GitHub Releases once.';
  }
  // Keep a short raw hint in the message so the tooltip reveals the real cause.
  return `Greenroom could not check for updates (${raw.slice(0, 140)}).`;
}

class UpdaterManager {
  private status: UpdateStatus = {
    phase: 'idle',
    currentVersion: app.getVersion(),
    supported: app.isPackaged,
  };
  private getWin: (() => BrowserWindow | null) | null = null;
  private initialized = false;
  private userInitiated = false;
  private checkTimer: NodeJS.Timeout | null = null;
  private upToDateTimer: NodeJS.Timeout | null = null;

  initialize(getWin: () => BrowserWindow | null): void {
    if (this.initialized) return;
    this.initialized = true;
    this.getWin = getWin;
    if (!app.isPackaged) return;

    autoUpdater.autoDownload = true;
    autoUpdater.autoInstallOnAppQuit = false;
    autoUpdater.on('checking-for-update', () => {
      this.clearUpToDateTimer();
      this.armWatchdog();
      this.setStatus({ phase: 'checking' });
    });
    autoUpdater.on('update-available', (info) => {
      this.clearWatchdog();
      this.setStatus({ phase: 'available', version: info.version });
    });
    autoUpdater.on('update-not-available', () => {
      this.clearWatchdog();
      // Positive confirmation for a manual check; quiet for background checks.
      const phase = this.userInitiated ? 'up-to-date' : 'idle';
      const checkedAt = Date.now();
      this.setStatus({ phase, lastCheckedAt: checkedAt });
      if (phase === 'up-to-date') this.returnToIdleAfterUpToDate(checkedAt);
      this.userInitiated = false;
    });
    autoUpdater.on('download-progress', (progress) => {
      this.clearWatchdog();
      this.setStatus({ phase: 'downloading', percent: progress.percent });
    });
    autoUpdater.on('update-downloaded', (info) => {
      this.clearWatchdog();
      this.setStatus({ phase: 'downloaded', version: info.version, lastCheckedAt: Date.now() });
      this.userInitiated = false;
    });
    autoUpdater.on('error', (error) => {
      this.clearWatchdog();
      console.error('[updater] check/download failed:', error);
      this.setStatus({
        phase: 'error',
        error: readableUpdateError(error),
        userInitiated: this.userInitiated,
        lastCheckedAt: Date.now(),
      });
      this.userInitiated = false;
    });

    setTimeout(() => void this.check(false), INITIAL_CHECK_DELAY_MS);
    setInterval(() => void this.check(false), CHECK_INTERVAL_MS);
  }

  getStatus(): UpdateStatus {
    return { ...this.status };
  }

  async check(userInitiated = true): Promise<UpdateStatus> {
    if (!app.isPackaged) return this.getStatus();
    if (this.status.phase === 'checking' || this.status.phase === 'downloading') return this.getStatus();
    this.userInitiated = userInitiated;
    if (userInitiated) this.prepareFreshManualCheck();
    try {
      await autoUpdater.checkForUpdates();
    } catch (error) {
      // checkForUpdates also emits 'error', but rejecting before that event
      // (e.g. bad app-update.yml) is why retry felt stuck — handle it here too.
      this.clearWatchdog();
      console.error('[updater] checkForUpdates rejected:', error);
      this.setStatus({
        phase: 'error',
        error: readableUpdateError(error instanceof Error ? error : new Error(String(error))),
        userInitiated,
        lastCheckedAt: Date.now(),
      });
      this.userInitiated = false;
    }
    return this.getStatus();
  }

  installNow(): void {
    if (this.status.phase === 'downloaded') autoUpdater.quitAndInstall(true, true);
  }

  private armWatchdog(): void {
    this.clearWatchdog();
    this.checkTimer = setTimeout(() => {
      if (this.status.phase !== 'checking') return;
      console.error('[updater] check timed out after', CHECK_TIMEOUT_MS, 'ms');
      this.setStatus({
        phase: 'error',
        error: 'The update check timed out. Check your connection and try again.',
        userInitiated: this.userInitiated,
        lastCheckedAt: Date.now(),
      });
      this.userInitiated = false;
    }, CHECK_TIMEOUT_MS);
  }

  private clearWatchdog(): void {
    if (this.checkTimer) {
      clearTimeout(this.checkTimer);
      this.checkTimer = null;
    }
  }

  private clearUpToDateTimer(): void {
    if (this.upToDateTimer) {
      clearTimeout(this.upToDateTimer);
      this.upToDateTimer = null;
    }
  }

  private returnToIdleAfterUpToDate(checkedAt: number): void {
    this.clearUpToDateTimer();
    this.upToDateTimer = setTimeout(() => {
      if (this.status.phase === 'up-to-date' && this.status.lastCheckedAt === checkedAt) {
        this.setStatus({ phase: 'idle', lastCheckedAt: checkedAt });
      }
      this.upToDateTimer = null;
    }, UP_TO_DATE_VISIBLE_MS);
  }

  private prepareFreshManualCheck(): void {
    // electron-updater keeps the provider instance alive for the process. Reset it
    // on manual checks so a just-published GitHub release is not hidden until app restart.
    const updater = autoUpdater as unknown as {
      clientPromise?: Promise<unknown> | null;
      updateInfoAndProvider?: unknown;
    };
    updater.clientPromise = null;
    updater.updateInfoAndProvider = null;
    autoUpdater.requestHeaders = {
      'Cache-Control': 'no-cache',
      Pragma: 'no-cache',
    };
  }

  private setStatus(update: Partial<UpdateStatus> & Pick<UpdateStatus, 'phase'>): void {
    this.status = {
      currentVersion: this.status.currentVersion,
      supported: this.status.supported,
      ...update,
    };
    this.getWin?.()?.webContents.send(IPC_EVENT.updaterStatus, this.getStatus());
  }
}

export const updaterManager = new UpdaterManager();
